// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBha74UoIJ6ya_DRntDNahjPe7dnLBCJ3Q',
    appId: '1:977891698478:web:2f0d153e1d56ee522f7cbf',
    messagingSenderId: '977891698478',
    projectId: 'skillswap-6d6fe',
    authDomain: 'skillswap-6d6fe.firebaseapp.com',
    storageBucket: 'skillswap-6d6fe.firebasestorage.app',
    measurementId: 'G-E0S9W76W6P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNeDrPIhSiUQCt1IPmBiSZyICNKlnQrwc',
    appId: '1:977891698478:ios:23539e607b2539952f7cbf',
    messagingSenderId: '977891698478',
    projectId: 'skillswap-6d6fe',
    storageBucket: 'skillswap-6d6fe.firebasestorage.app',
    iosClientId: '977891698478-stc4maauit9m6ska5tkpng6ba4u35a5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillswap',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNeDrPIhSiUQCt1IPmBiSZyICNKlnQrwc',
    appId: '1:977891698478:ios:23539e607b2539952f7cbf',
    messagingSenderId: '977891698478',
    projectId: 'skillswap-6d6fe',
    storageBucket: 'skillswap-6d6fe.firebasestorage.app',
    iosClientId: '977891698478-stc4maauit9m6ska5tkpng6ba4u35a5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBha74UoIJ6ya_DRntDNahjPe7dnLBCJ3Q',
    appId: '1:977891698478:web:2f0d153e1d56ee522f7cbf',
    messagingSenderId: '977891698478',
    projectId: 'skillswap-6d6fe',
    authDomain: 'skillswap-6d6fe.firebaseapp.com',
    storageBucket: 'skillswap-6d6fe.firebasestorage.app',
    measurementId: 'G-E0S9W76W6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_x176NIIMYg110GGKwP84USmzAWjNepo',
    appId: '1:977891698478:android:b5f08858eced213e2f7cbf',
    messagingSenderId: '977891698478',
    projectId: 'skillswap-6d6fe',
    storageBucket: 'skillswap-6d6fe.firebasestorage.app',
  );
}
